### ISSUE TITLE
example is using deprecated private variable

### ISSUE THREAD

**Issue by grawk** [paypal/nemo#115]
`examples/setup.js` is trying to get the browserName property from a `caps_` variable which is no longer available in recent versions of selenium-webdriver. Encountering this error:

```bash
$ cd node_modules/nemo/examples/
LM-SJN-00872356:examples medelman$ node setup.js 
Error during Nemo setup [TypeError: Cannot read property 'browserName' of undefined]
/Users/medelman/src/_nemo/o/nemo-example-app/node_modules/nemo/node_modules/selenium-webdriver/lib/promise.js:654
    throw error;
    ^

TypeError: Cannot read property 'browserName' of undefined
    at /Users/medelman/src/_nemo/o/nemo-example-app/node_modules/nemo/examples/setup.js:17:60
    at ManagedPromise.invokeCallback_ (/Users/medelman/src/_nemo/o/nemo-example-app/node_modules/nemo/node_modules/selenium-webdriver/lib/promise.js:1343:14)
    at TaskQueue.execute_ (/Users/medelman/src/_nemo/o/nemo-example-app/node_modules/nemo/node_modules/selenium-webdriver/lib/promise.js:2868:14)
    at TaskQueue.executeNext_ (/Users/medelman/src/_nemo/o/nemo-example-app/node_modules/nemo/node_modules/selenium-webdriver/lib/promise.js:2851:21)
    at /Users/medelman/src/_nemo/o/nemo-example-app/node_modules/nemo/node_modules/selenium-webdriver/lib/promise.js:2730:27
    at /Users/medelman/src/_nemo/o/nemo-example-app/node_modules/nemo/node_modules/selenium-webdriver/lib/promise.js:639:7
    at process._tickCallback (node.js:368:9)

```

**Comment by nikulkarni** [comment]
Fixed as part of #128
