### ISSUE TITLE
Issues creating nemo instances

### ISSUE THREAD

**Issue by jonathansamines** [paypal/nemo#166]
Somehow, while migrating our existing functional test from nemo 2.3.1 to 2.4.1 they just stop working. They keep breaking at [L198](https://github.com/paypal/nemo-screenshot/blob/v2.2.2/index.js#L198) from nemo-screenshot with the following trace:

```
TypeError: Cannot read property 'then' of undefined
      at node_modules/nemo-screenshot/index.js:198:36
      at ControlFlow.emit (node_modules/selenium-webdriver/lib/events.js:64:21)
      at ControlFlow.execute (node_modules/selenium-webdriver/lib/promise.js:2252:10)
      at Function.createSession (node_modules/selenium-webdriver/lib/webdriver.js:329:24)
      at Driver (node_modules/selenium-webdriver/phantomjs.js:192:38)
      at Builder.build (node_modules/selenium-webdriver/builder.js:479:16)
      at Object.doSetup [as setup] (node_modules/nemo/lib/driver.js:122:26)
      at driversetup (node_modules/nemo/lib/setup.js:57:16)
      at fn (node_modules/nemo/node_modules/async/lib/async.js:746:34)
      at node_modules/nemo/node_modules/async/lib/async.js:1213:16
      at node_modules/nemo/node_modules/async/lib/async.js:166:37
      at node_modules/nemo/node_modules/async/lib/async.js:706:43
      at node_modules/nemo/node_modules/async/lib/async.js:167:37
      at Immediate.<anonymous> (node_modules/nemo/node_modules/async/lib/async.js:1206:34)
```

I am not really sure why selenium started to return "undefined" for the `driver.getSession()` method. Perhaps something at the Setup/Configure separation broke that?

Any help is appreciated. Thanks!

**Comment by aniljca** [comment]
@jonathansamines - Can you try to use nemo-screenshot@2.2.3 and let us know if if it fixes this issue? We saw a similar issue and just pushed the fix.

**Comment by grawk** [comment]
Right. that should resolve the issue.

**Comment by jonathansamines** [comment]
I can confirm, it is working now. Thanks!
